baseURL = 'https://svipy.com/'
title = "Pavel Sviridov"
# theme = "ananke"
languagecode = "en-us"
defaultcontentlanguage = "en"

[pagination]
pagerSize = 20

# disqusShortname = "yourdiscussshortname"

[markup.highlight]
style = "github-dark"

[params]
  author = "Pavel Sviridov"
  info = "Awesome Backend Developer and Team Leader"
  description = "Pavel Sviridov's personal website"
  keywords = "blog,developer,personal"
  since = 2023

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Telegram"
  url = "https://t.me/svipy/"
[[params.social]]
  name = "LinkedIn"
  url = "https://linkedin.com/in/svipy/"
[[params.social]]
  name = "Medium"
  url = "https://medium.com/@sviridov.py"
[[params.social]]
  name = "GitHub"
  url = "https://github.com/svipy9/"


# Menu links
# [[menu.main]]
#  name = "Blog"
#  weight = 1
#  url  = "posts/"
[[menu.main]]
  name = "About"
  weight = 2
  url = "about/"
