baseURL = 'https://svipy.com/'
title = "Pavel Sviridov"
theme = "PaperMod"
languagecode = "en-us"
defaultcontentlanguage = "en"

[pagination]
pagerSize = 20

[markup.highlight]
style = "github-dark"

[params]
  author = "Pavel Sviridov"
  description = "CTO at TripleTen, Berlin"
  keywords = ["backend", "python", "golang", "team-leader", "edtech"]
  
  # Profile section
  [params.profileMode]
    enabled = true
    title = "Pavel Sviridov"
    subtitle = "CTO at TripleTen"
    imageUrl = "https://www.gravatar.com/avatar/e890a97035f61d0fd98a1e679e59caa0?s=400"
    imageTitle = "Pavel Sviridov"
  
  # PaperMod specific
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowWordCount = true
  ShowRssButtonInSectionTermList = true
  UseHugoToc = true
  disableSpecial1stPost = false
  disableScrollToTop = false
  comments = false
  hidemeta = false
  hideSummary = false
  showtoc = true
  tocopen = false

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links for PaperMod
[[params.socialIcons]]
  name = "telegram"
  url = "https://t.me/svipy/"
[[params.socialIcons]]
  name = "linkedin"
  url = "https://linkedin.com/in/svipy/"
[[params.socialIcons]]
  name = "medium"  
  url = "https://medium.com/@sviridov.py"
[[params.socialIcons]]
  name = "github"
  url = "https://github.com/svipy9/"

# Menu links
[[menu.main]]
  identifier = "posts"
  name = "Blog"
  url = "/posts"
  weight = 1

[[menu.main]]
  identifier = "about"
  name = "About"
  url = "/about"
  weight = 2